baseURL = 'https://jeremyklein.github.io/blog/'
languageCode = 'en-us'
title = 'Jeremy Klein Blog'
theme = "soho"

[params]
  description = "Personal blog and thoughts"
  
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
