baseURL = 'https://jeremyklein.github.io/blog/'
languageCode = 'en-us'
title = 'Jeremy Klein Blog'
theme = "soho"

[params]
  description = "Personal blog and thoughts"
  
  [[params.socialIcons]]
    icon = "fa-linkedin-in"
    title = "LinkedIn"
    url = "https://linkedin.com/in/jeremy-klein/"
  
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
